### ISSUE TITLE
Number of senders in benchmarks

### ISSUE THREAD

**Issue by jumpnbrownweasel** [mahdi-shojaee/loole#5]
Hello!  I noticed that the benchmark code has MAX_SENDERS set to 2000 but the charts show 5000 in the title. Were the benchmarks run with a MAX_SENDERS set to 5000?

I am comparing the lool benchmarks to the kanal benchmarks and they show radically different results so I check the benchmark code. It seems one big difference is the number of senders. With the sync tests (which is what I'm interested in), kanal only uses 4 threads total, even though the hardware has 16 cores.

Do you have any thoughts about the cause of the differences between lool and kanal when it comes to number of senders, particularly for MPSC sync?

**Comment by mahdi-shojaee** [comment]
Hi, thanks for your feedback!

> I noticed that the benchmark code has MAX_SENDERS set to 2000, but the charts show 5000 in the title.

You're right. You can change MAX_SENDERS to 5000 and rerun the benchmarks if you'd like. However, from my testing, 5000 senders can be too high for macOS.

> Were the benchmarks run with MAX_SENDERS set to 5000?

The benchmarks were run on the following setup:
OS: Ubuntu Linux 23.10
Kernel: 6.5.0-13
CPU: Intel Core i7-13700K (16 cores / 24 threads)

> With the sync tests (which is what I'm interested in), kanal only uses 4 threads total, even though the hardware has 16 cores.

In my experience, I haven't observed this behavior. It seems that kanal utilizes all available cores similarly to other implementations. The number of cores used can depend on the async runtime (e.g., Tokio, async-std, etc.).

**Comment by mahdi-shojaee** [comment]
Hi, thanks for your participation!

> I noticed that the benchmark code has MAX_SENDERS set to 2000, but the charts show 5000 in the title.

You can change the MAX_SENDERS to 5000 and rerun the benchmarks. However, in my experience, 5000 senders is too large for macOS, and benchmark results tend to vary significantly on that platform.

> Were the benchmarks run with MAX_SENDERS set to 5000?

Yes, the benchmarks were run on the following system:

OS: Ubuntu Linux 23.10
Kernel: 6.5.0-13
CPU: Intel Core i7-13700K (16 cores, 24 threads)

> With the sync tests (which is what I'm interested in), kanal only uses 4 threads total, even though the hardware has 16 cores.

From my testing, I haven't observed this behavior. It seems that kanal does utilize all available cores, similar to other implementations. The number of cores used can also be configured in the async runtime (e.g., Tokio, async-std, etc.).

**Comment by mahdi-shojaee** [comment]
Hi, thanks for your feedback!

> I noticed that the benchmark code has MAX_SENDERS set to 2000, but the charts show 5000 in the title.

You can change the MAX_SENDERS to 5000 and rerun the benchmarks. However, in my experience, 5000 senders is too large for macOS, and benchmark results tend to vary significantly on that platform.

> Were the benchmarks run with MAX_SENDERS set to 5000?

The benchmarks were run on the following system:

- OS: Ubuntu Linux 23.10
- Kernel: 6.5.0-13
- CPU: Intel Core i7-13700K (16 cores, 24 threads)

> With the sync tests (which is what I'm interested in), kanal only uses 4 threads total, even though the hardware has 16 cores.

From my testing, I haven't observed this behavior. It seems that kanal does utilize all available cores, similar to other implementations. The number of cores used can also be configured in the async runtime (e.g., Tokio, async-std, etc.).
